package gitops

import (
	"fmt"
	"strings"
)

// FluxRenderer produces the Flux-only files of the layout from the
// engine-neutral ones. They must be byte-identical to what
// okdp-sandbox/gitops/scripts/render-flux.sh produces: that script is the
// reference (its format is specified in okdp-sandbox/gitops/README.md,
// "Generated files (Flux): byte-exact format"), its check.sh diffs the two in
// CI, and the golden tests of this package replay its fixtures.
type FluxRenderer interface {
	// RenderInstance returns the generated files of a service directory, keyed
	// by file name (helmrelease.yaml, kustomization.yaml).
	RenderInstance(inst Instance) (map[string][]byte, error)
	// RenderProject returns projects/<p>/kustomization.yaml for the given
	// services (sub-directories holding an instance.yaml) and connections
	// (connection file names without .yaml), both sorted.
	RenderProject(project string, services, connections []string) ([]byte, error)
}

// FluxHeader is the first line of every generated file. render-flux.sh uses
// it to recognise the files it owns.
const FluxHeader = "# Generated by scripts/render-flux.sh. Do not edit."

// DefaultFluxRenderer renders the format of render-flux.sh: fixed templates,
// values from instance.yaml and from names written inside double quotes
// (validation guarantees they hold no quote nor backslash).
type DefaultFluxRenderer struct{}

// NewDefaultFluxRenderer returns the renderer of the reference format.
func NewDefaultFluxRenderer() *DefaultFluxRenderer { return &DefaultFluxRenderer{} }

// ConnectionValuesName and InstanceValuesName are the names of the values
// ConfigMaps in okdp-releases, after okdp-platform-values in layering order.
func ConnectionValuesName(project, name string) string {
	return fmt.Sprintf("conn-%s-%s", project, name)
}

func InstanceValuesName(project, instance string) string {
	return fmt.Sprintf("values-%s-%s", project, instance)
}

type lines struct{ b strings.Builder }

func (l *lines) add(format string, args ...any) {
	fmt.Fprintf(&l.b, format, args...)
	l.b.WriteByte('\n')
}

func (r *DefaultFluxRenderer) RenderInstance(inst Instance) (map[string][]byte, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	p, rel := inst.Project, inst.ReleaseName()

	var hr lines
	hr.add("%s", FluxHeader)
	hr.add("---")
	hr.add("apiVersion: source.toolkit.fluxcd.io/v1")
	hr.add("kind: OCIRepository")
	hr.add("metadata:")
	hr.add("  name: %q", rel)
	hr.add("  namespace: %s", ReleasesNamespace)
	hr.add("  labels:")
	hr.add("    okdp.io/project: %q", p)
	hr.add("    okdp.io/instance: %q", rel)
	hr.add("spec:")
	hr.add("  interval: 10m")
	hr.add("  url: %q", inst.Chart)
	hr.add("  ref:")
	hr.add("    tag: %q", inst.Version)
	hr.add("  layerSelector:")
	hr.add("    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip")
	hr.add("    operation: copy")
	hr.add("---")
	hr.add("apiVersion: helm.toolkit.fluxcd.io/v2")
	hr.add("kind: HelmRelease")
	hr.add("metadata:")
	hr.add("  name: %q", rel)
	hr.add("  namespace: %s", ReleasesNamespace)
	hr.add("  labels:")
	hr.add("    okdp.io/project: %q", p)
	hr.add("    okdp.io/instance: %q", rel)
	hr.add("spec:")
	hr.add("  interval: 10m")
	hr.add("  releaseName: %q", rel)
	hr.add("  targetNamespace: %q", p)
	hr.add("  storageNamespace: %q", p)
	hr.add("  chartRef:")
	hr.add("    kind: OCIRepository")
	hr.add("    name: %q", rel)
	hr.add("  timeout: 15m")
	hr.add("  install:")
	hr.add("    createNamespace: true")
	hr.add("    strategy:")
	hr.add("      name: RetryOnFailure")
	hr.add("      retryInterval: 2m")
	hr.add("  upgrade:")
	hr.add("    remediation:")
	hr.add("      retries: 3")
	hr.add("      strategy: rollback")
	hr.add("  driftDetection:")
	hr.add("    mode: enabled")
	hr.add("  valuesFrom:")
	hr.add("    - kind: ConfigMap")
	hr.add("      name: %s", PlatformValuesConfigMap)
	hr.add("      valuesKey: %s", ValuesKey)
	for _, c := range inst.Connections {
		hr.add("    - kind: ConfigMap")
		hr.add("      name: %q", ConnectionValuesName(p, c))
		hr.add("      valuesKey: %s", ValuesKey)
	}
	hr.add("    - kind: ConfigMap")
	hr.add("      name: %q", InstanceValuesName(p, inst.Name))
	hr.add("      valuesKey: %s", ValuesKey)

	var k lines
	k.add("%s", FluxHeader)
	k.add("apiVersion: kustomize.config.k8s.io/v1beta1")
	k.add("kind: Kustomization")
	k.add("namespace: %s", ReleasesNamespace)
	k.add("resources:")
	k.add("  - %s", HelmReleaseFile)
	k.add("configMapGenerator:")
	k.add("  - name: %q", InstanceValuesName(p, inst.Name))
	k.add("    files:")
	k.add("      - %s", ValuesFile)
	k.add("    options:")
	k.add("      disableNameSuffixHash: true")
	k.add("      labels:")
	k.add("        reconcile.fluxcd.io/watch: Enabled")

	return map[string][]byte{
		HelmReleaseFile:   []byte(hr.b.String()),
		KustomizationFile: []byte(k.b.String()),
	}, nil
}

func (r *DefaultFluxRenderer) RenderProject(project string, services, connections []string) ([]byte, error) {
	if err := ValidateName("project", project); err != nil {
		return nil, err
	}
	var k lines
	k.add("%s", FluxHeader)
	k.add("apiVersion: kustomize.config.k8s.io/v1beta1")
	k.add("kind: Kustomization")
	k.add("namespace: %s", ReleasesNamespace)
	if len(services) == 0 {
		k.add("resources: []")
	} else {
		k.add("resources:")
		for _, s := range services {
			k.add("  - services/%s", s)
		}
	}
	if len(connections) == 0 {
		k.add("configMapGenerator: []")
	} else {
		k.add("configMapGenerator:")
		for _, c := range connections {
			k.add("  - name: %q", ConnectionValuesName(project, c))
			k.add("    files:")
			k.add("      - %s=connections/%s.yaml", ValuesKey, c)
			k.add("    options:")
			k.add("      disableNameSuffixHash: true")
			k.add("      labels:")
			k.add("        reconcile.fluxcd.io/watch: Enabled")
		}
	}
	return []byte(k.b.String()), nil
}
