package gitops

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// FluxRenderer produces the Flux-only files of the layout from the
// engine-neutral ones. They must be byte-identical to what
// okdp-sandbox/gitops/scripts/render-flux.sh produces: that script is the
// reference, CI (scripts/check.sh) diffs the two, and this interface is where
// the format is swapped when the reference changes.
type FluxRenderer interface {
	// RenderInstance returns the generated files of a service directory, keyed
	// by file name (helmrelease.yaml, kustomization.yaml).
	RenderInstance(inst Instance) (map[string][]byte, error)
	// RenderConnections returns the generated files of a project's connections
	// directory for the given connection names (sorted), keyed by file name.
	// No names means the generated files are removed.
	RenderConnections(project string, names []string) (map[string][]byte, error)
}

// Chart layer media type of a Helm chart pushed to an OCI registry.
const helmChartLayerMediaType = "application/vnd.cncf.helm.chart.content.v1.tar+gzip"

// DefaultFluxRenderer implements the format described by the shared contract
// (HelmRelease + OCIRepository in okdp-releases, values ConfigMaps generated by
// kustomize and layered through valuesFrom).
//
// TODO(no-kubocd): align on okdp-sandbox/gitops/README.md once published and
// replace the golden fixtures with the ones render-flux.sh produces.
type DefaultFluxRenderer struct {
	// Interval of the OCIRepository and the HelmRelease.
	Interval string
}

// NewDefaultFluxRenderer returns the renderer with the contract defaults.
func NewDefaultFluxRenderer() *DefaultFluxRenderer {
	return &DefaultFluxRenderer{Interval: "10m"}
}

// PlatformValuesName, ConnectionValuesName and InstanceValuesName are the
// names of the values ConfigMaps, in layering order.
func ConnectionValuesName(project, name string) string {
	return fmt.Sprintf("conn-%s-%s", project, name)
}
func InstanceValuesName(project, instance string) string {
	return fmt.Sprintf("values-%s-%s", project, instance)
}

func (r *DefaultFluxRenderer) RenderInstance(inst Instance) (map[string][]byte, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	release := inst.ReleaseName()

	valuesFrom := seq(valuesRef(PlatformValuesConfigMap))
	for _, c := range inst.Connections {
		valuesFrom.Content = append(valuesFrom.Content, valuesRef(ConnectionValuesName(inst.Project, c)))
	}
	valuesFrom.Content = append(valuesFrom.Content, valuesRef(InstanceValuesName(inst.Project, inst.Name)))

	ociRepository := mapping(
		"apiVersion", str("source.toolkit.fluxcd.io/v1"),
		"kind", str("OCIRepository"),
		"metadata", mapping(
			"name", str(release),
			"namespace", str(ReleasesNamespace),
		),
		"spec", mapping(
			"interval", str(r.Interval),
			"url", str(inst.Chart),
			"ref", mapping("tag", str(inst.Version)),
			"layerSelector", mapping(
				"mediaType", str(helmChartLayerMediaType),
				"operation", str("copy"),
			),
		),
	)
	helmRelease := mapping(
		"apiVersion", str("helm.toolkit.fluxcd.io/v2"),
		"kind", str("HelmRelease"),
		"metadata", mapping(
			"name", str(release),
			"namespace", str(ReleasesNamespace),
			"labels", mapping(
				"okdp.io/project", str(inst.Project),
				"okdp.io/instance", str(release),
				"okdp.io/service", str(inst.Service),
			),
		),
		"spec", mapping(
			"interval", str(r.Interval),
			"releaseName", str(release),
			"targetNamespace", str(inst.Project),
			"storageNamespace", str(inst.Project),
			"chartRef", mapping(
				"kind", str("OCIRepository"),
				"name", str(release),
			),
			"valuesFrom", valuesFrom,
		),
	)

	hr, err := encodeDocuments(ociRepository, helmRelease)
	if err != nil {
		return nil, err
	}

	kustomization := mapping(
		"apiVersion", str("kustomize.config.k8s.io/v1beta1"),
		"kind", str("Kustomization"),
		"namespace", str(ReleasesNamespace),
		"resources", seq(str(HelmReleaseFile)),
		"configMapGenerator", seq(configMapGenerator(InstanceValuesName(inst.Project, inst.Name), ValuesKey+"="+ValuesFile)),
	)
	k, err := encodeDocuments(kustomization)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{HelmReleaseFile: hr, KustomizationFile: k}, nil
}

func (r *DefaultFluxRenderer) RenderConnections(project string, names []string) (map[string][]byte, error) {
	if len(names) == 0 {
		return map[string][]byte{}, nil
	}
	generators := seq()
	for _, name := range names {
		generators.Content = append(generators.Content,
			configMapGenerator(ConnectionValuesName(project, name), ValuesKey+"="+name+".yaml"))
	}
	kustomization := mapping(
		"apiVersion", str("kustomize.config.k8s.io/v1beta1"),
		"kind", str("Kustomization"),
		"namespace", str(ReleasesNamespace),
		"configMapGenerator", generators,
	)
	k, err := encodeDocuments(kustomization)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{KustomizationFile: k}, nil
}

func valuesRef(configMap string) *yaml.Node {
	return mapping(
		"kind", str("ConfigMap"),
		"name", str(configMap),
		"valuesKey", str(ValuesKey),
	)
}

func configMapGenerator(name, file string) *yaml.Node {
	return mapping(
		"name", str(name),
		"files", seq(str(file)),
		"options", mapping(
			"disableNameSuffixHash", boolean(true),
			"labels", mapping("reconcile.fluxcd.io/watch", str("Enabled")),
		),
	)
}

// --- yaml.Node builders: the output order is the declaration order ---

func str(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}
}

func boolean(v bool) *yaml.Node {
	value := "false"
	if v {
		value = "true"
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: value}
}

func seq(items ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq", Content: items}
}

// mapping takes alternating keys (string) and values (*yaml.Node).
func mapping(pairs ...any) *yaml.Node {
	n := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	for i := 0; i+1 < len(pairs); i += 2 {
		n.Content = append(n.Content, str(pairs[i].(string)), pairs[i+1].(*yaml.Node))
	}
	return n
}

func encodeDocuments(docs ...*yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	for _, d := range docs {
		if err := enc.Encode(&yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{d}}); err != nil {
			return nil, err
		}
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
